# Regresi Linier Berganda

Regresi linier berganda (*multiple linear regression*) adalah pengembangan dari regresi linier sederhana.  Dengan regresi linier berganda, kita dapat memasukkan lebih dari satu variabel penjelas ke dalam model. Hal ini dikarenakan di dalam praktik model yang kita pakai kemungkinan melibatkan lebih dari satu variabel prediktor.

Pengembangan ini bermanfaat jika dilihat dari dua sisi. Sisi pertama, penambahan variabel penjelas dapat memberikan penjelasan yang lebih lengkap tentang variabel respons, karena jarang suatu fenomena hanya disebabkan oleh hanya satu hal. Kedua, dampak dari variabel prediktor tertentu dibuat lebih terang, karena kemungkinan dampak distorsi dari variabel prediktor yang lain dihilangkan.

Pemahaman dasar-dasar dari regresi linier sederhana sangat penting untuk memahami  regresi linier berganda yang lebih rumit. Dengan bantuan program komputer, proses estimasi dan interpretasi parameter mengikuti prinsip-prinsip yang sama. Begitu juga dengan uji signifikansi, koefisien determinasi ($R^2$) dan asumsi-asumsi pada regresi linier sederhana terus dibawa ke dalam regresi linier berganda. 

Hal-hal yang harus diperhatikan karena berpotensi menjadi masalah dalam melakukan analisis regresi adalah isu-isu yang berhubungan (1) *overfitting*, (2) heteroskedastisitas, (3) multikolinearitas. Teknik regresi berganda sangat luas cakupannya. Penguasaan teknik regresi berganda akan memberikan bekal yang sangat berharga untuk menganalisis berbagai jenis data kuantitatif.  

## Persamaan Umum

Secara umum, di dalam persamaan regresi berganda variabel respons dipandang sebagai fungsi linier dari *lebih dari satu* variabel prediktor $1>p$.

\begin{equation} 
y_i=\beta_0 + \beta_1x_{i1} + \beta_2x_{i2} + ... + \beta_px_{ip} + \epsilon_i
(\#eq:persamaan-ganda)
\end{equation}


Untuk model dengan dua variabel prediktor saja, persamaannya dapat dituliskan sebagai:

\begin{equation} 
y_i=\beta_0 + \beta_1x_{i1} + \beta_2x_{i2} + \epsilon_i
(\#eq:persamaan-2var)
\end{equation}

yang menunjukkan bahwa y ditentukan oleh $x_1$ dan $x_2$, ditambah faktor kesalahan. Untuk mengestimasi nilai-nilai parameter, kita gunakan prinsip kuadrat kesalahan terkecil (*the least squares principle*), dengan meminimalkan jumlah kuadrat kesalahan prediksi (SSE):

\begin{equation}
SSE = \Sigma(y - \hat y)^2
(\#eq:persamaan-sse)
\end{equation}

Koefisien-koefisien yang diperoleh yaitu ($\beta_0, \beta_1, \beta_2$) menghasilkan kesalahan prediksi paling kecil dibandingkan kombinasi-kombinasi koefisien yang lain.
Tetapi disini kita tidak dapat lagi menampilkan diagram pencar pada bidang dua dimensi. Kita harus menampilkan perpencaran datanya pada bidang tiga dimensi. Lokasi dari garis pada bidang tiga dimensi ini ditentukan oleh besaran nilai-nilai ($\beta_0, \beta_1, \beta_2$). Jika variabel penjelasnya lebih dari tiga, perpencaran datanya sangat sulit untuk dibayangkan atau digambarkan.

::: {.rmdnote}
Buku ini adalah versi *online*. Jika Anda berminat untuk membaca versi lengkapnya, Anda bisa membeli versi **cetaknya** di toko-toko buku.
:::
